routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//admin
Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function(){
    Route::get('/admin', function () {
        return view('admin/welcome');
    });
    
    Route::resource('products','ProductController');
    Route::resource('categories','CategoryController');
    Route::resource('generals','GeneralController');
    Route::resource('admin', 'VisitorController');
});


//customer
Route::resource('/', 'CustomerController')->names([
    'index' => 'home customer',
    // 'indexkategori' => 'indexkategoricust',
    // 'indexproduk' => 'indexprodukcust',
    // 'indexkontak' => 'indexkontakcust'
]);
// Route::resource('/', 'VisitorController');
Route::get('kategori/', 'CustomerController@indexkategori')->name("kategoricust");
Route::get('kategori/{nama_kategori}/', 'CustomerController@detailkategori')->name("listkategoriproduk");
Route::get('produk/', 'CustomerController@indexproduk')->name("produkcust");
Route::get('produk/{nama_produk}/', 'CustomerController@detailproduk')->name('detailproduk');
Route::get('kontak/', 'CustomerController@indexkontak')->name("kontakcust");

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'categories';

    // primary key pada database yaitu idcategories (default dari laravel yaitu id)
    protected $primaryKey = 'idcategories';

    // di category kita bisa ambil products (pake s krn banyak), karena satu kategori banyak products maka pake hasMany
    // nama fungsi products bebas, yang penting esensinya kumpulan products 
    public function products() {
        //parameter berisi namespace\namaModel
        return $this->hasMany("App\Product","categories_id","idcategories");
    }

    public $timestamps = false; //biar nggak error pas tambah supplier karena default dari laravel pakai timestamp, sedangkan kita ngga pakai timestamp
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;
use App\Category;
use App\Product;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use DB;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //Query dengan model
        // tampil pada halaman kategori admin
        return view('admin.category.index',['data'=>Category::all()]); //yg dikirim model nya. all() artinya array
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.createform');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // return $request->file('image')->store('imageCategories');

        //untuk validasi saat user mengisi data, apabila ada yang masih kosong dimunculkan pesan error
        $request->validate([
            'nmKategori' => 'required',
            'image' => 'required|image|file|max:10240', //max 10mb (10240kb)
            'deskKategori' => 'required',
        ], [
            'nmKategori.required' => 'Nama kategori tidak boleh kosong',
            'image.required' => 'Gambar kategori tidak boleh kosong',
            'deskKategori.required' => 'Deskripsi kategori tidak boleh kosong',
        ]);     
        
        //New Kategori berarti artinya new Data Kategori (insert)
        $data = new Category();

        //$data->[nama_kolom_pada_db] = $request->get('[name dari input text]')
        $data->nama_kategori = $request->get('nmKategori');
        if($request->file('image')) {
            $data['gambar_kategori'] = $request->file('image')->store('imageCategories');
        }
        $data->deskripsi_kategori = $request->get('deskKategori');
        $data->save();
        
        //akan memanggil route kategori index yang akan kembali ke halaman utama Kategori 
        //dengan menambahkan session status yang isinya berhasil ditambahkan Kategori baru
        //with = membuat session sementara bernama status yg menampilkan berhasilnya ditambahkan data Kategori 
        return redirect()->route('categories.index')->with('status','Data Kategori berhasil ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $data = $category;
        return view('admin/category/editform',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //untuk validasi saat user mengisi data, apabila ada yang masih kosong dimunculkan pesan error
        $request->validate([
            'nmKategori' => 'required',
            'image' => 'image|file|max:10240', //max 10mb (10240kb)
            'deskKategori' => 'required',
        ], [
            'nmKategori.required' => 'Nama kategori tidak boleh kosong',
            'deskKategori.required' => 'Deskripsi kategori tidak boleh kosong',
        ]);     

        $category->nama_kategori = $request->get('nmKategori');
        if($request->file('image')) {
            if($request->oldImage) { //jika ada gambar lama di delete dulu
                Storage::delete($request->oldImage);
            }
            $category['gambar_kategori'] = $request->file('image')->store('imageCategories'); //upload gambar baru
        }
        $category->deskripsi_kategori = $request->get('deskKategori');
        $category->save();
        
        return redirect()->route('categories.index')->with('status', 'Data kategori berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        try {
            if($category->gambar_kategori) { //delete file gambar
                Storage::delete($category->gambar_kategori);
            }
            $category->delete();
            return redirect()->route('categories.index')->with('statushapus', 'Data kategori berhasil dihapus');
        } catch (\PDOException $e) {
            $msg = $this->handleAllRemoveChild($category);
            return redirect()->route('categories.index')->with('statushapus',
                $msg);
        }
    }
    //ini untuk menghapus data child (product)
    private function handleAllRemoveChild($s) {
        $s->products()->delete();
        $s->delete();
        return "Data kategori berhasil dihapus beserta data produk yang berkaitan";
    }
}

resources/views/admin/category/createform.blade.php
<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1"> -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> -->
<!-- </head>
<body>

<div class="container"> -->
@extends("admin.layout.conquer")

@section("left_sidebar")
<li class="sidebar-toggler-wrapper">
    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
    <div class="sidebar-toggler">
    </div>
    <div class="clearfix">
    </div>
    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
</li>
<li class="sidebar-search-wrapper">
    <form class="search-form" role="form" action="index.html" method="get">
        <div class="input-icon right">
            <i class="icon-magnifier"></i>
            <input type="text" class="form-control" name="query" placeholder="Search...">
        </div>
    </form>
</li>
<li>
    <a href="{{url('/admin')}}">
    <i class="icon-home"></i>
    <span class="title">Dashboard</span>
    <span class="selected"></span>
    </a>
</li>
<li class="active">
    <a href="{{route('categories.index')}}">
        <i class="icon-layers"></i>
        Kategori</a>
    </a>
</li>
<li>
    <a href="{{route('products.index')}}">
        <i class="icon-present"></i>
        Produk</a>
    </a>
</li>
<li >
    <a href="{{route('generals.index')}}">
        <i class="icon-docs"></i>
        Kontak</a>
</li>
@endsection

@section("konten")
<div class="page-content">
<div class="portlet">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-reorder"></i> Tambah Data Kategori
			</div>
		</div>
		<div class="portlet-body form">
			<form method="POST" action="{{ route('categories.store') }}" enctype="multipart/form-data">
			@csrf
				<div class="form-body">
					<div class="mb-3">
						<label for="image" class="form-label">Gambar</label> 
						<input class="form-control" type="file" id="image" name="image" onchange="document.getElementById('img-preview').src = window.URL.createObjectURL(this.files[0])">
						<img class="img-fluid" id="img-preview" style="max-height:400px">
						@error('image')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div><br>
					<div class="form-group">
						<label for="nmKategori">Nama</label>
						<input type="text" class="form-control @error('nmKategori') is-invalid @enderror" name="nmKategori" value="{{ old('nmKategori') }}" placeholder="Isikan nama kategori Anda">
						@error('nmKategori')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div><br>
					<div class="form-group">
						<label for="deskKategori">Deskripsi</label>
						<textarea class="form-control @error('deskKategori') is-invalid @enderror" name="deskKategori" placeholder="Isikan deskripsi kategori Anda" rows="3">{{ old('deskKategori') }}</textarea>
						@error('deskKategori')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div>
				</div>
				<div class="form-actions">
					<button type="submit" class="btn btn-primary">Simpan</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection
<!-- </body>
</html> -->

resources/views/admin/category/editform.blade.php
<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1"> -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> -->
<!-- </head>
<body>

<div class="container"> -->
@extends("admin.layout.conquer")

@section("left_sidebar")
<li class="sidebar-toggler-wrapper">
    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
    <div class="sidebar-toggler">
    </div>
    <div class="clearfix">
    </div>
    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
</li>
<li class="sidebar-search-wrapper">
    <form class="search-form" role="form" action="index.html" method="get">
        <div class="input-icon right">
            <i class="icon-magnifier"></i>
            <input type="text" class="form-control" name="query" placeholder="Search...">
        </div>
    </form>
</li>
<li>
    <a href="{{url('/admin')}}">
    <i class="icon-home"></i>
    <span class="title">Dashboard</span>
    <span class="selected"></span>
    </a>
</li>
<li class="active">
    <a href="{{route('categories.index')}}">
        <i class="icon-layers"></i>
        Kategori</a>
    </a>
</li>
<li>
    <a href="{{route('products.index')}}">
        <i class="icon-present"></i>
        Produk</a>
    </a>
</li>
<li >
    <a href="{{route('generals.index')}}">
        <i class="icon-docs"></i>
        Kontak</a>
</li>
@endsection

@section("konten")
<div class="page-content">
<div class="portlet">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-reorder"></i> Ubah Data Kategori
			</div>
		</div>
		<div class="portlet-body form">
			<form method="POST" action="{{ route('categories.update', $data->idcategories) }}" enctype="multipart/form-data">
			@csrf
			@method("PUT")
				<div class="form-body">
					<div class="mb-3">
                        <label for="image" class="form-label">Gambar</label> 
                        <input type="hidden" name="oldImage" value="{{ $data->gambar_kategori }}"> 
                        <input class="form-control @error('image') is-invalid @enderror" type="file" id="image" name="image"  onchange="document.getElementById('img-preview').src = window.URL.createObjectURL(this.files[0])">
                        @if($data->gambar_kategori)
                            <img src="{{ asset('storage/' . $data->gambar_kategori) }}" class="img-fluid" id="img-preview" style="max-height:400px">
                      	@else
                            <img class="img-fluid" id="img-preview" style="max-height:400px">
                            @error('image')
                                <div class="invalid-feedback" style="color:red">{{ $message }}</div>
                            @enderror
                        @endif
                    </div><br> 
					<div class="form-group">
						<label for="nmKategori">Nama</label>
						<input type="text" class="form-control @error('nmKategori') is-invalid @enderror" name="nmKategori" value="{{ old('nmKategori', $data->nama_kategori) }}" placeholder="Isikan nama kategori Anda">
						@error('nmKategori')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div><br>
					<div class="form-group">
						<label for="deskKategori">Deskripsi</label>
						<textarea class="form-control @error('deskKategori') is-invalid @enderror" name="deskKategori" placeholder="Isikan deskripsi kategori Anda" rows="3">{{ old('deskKategori', $data->deskripsi_kategori) }}</textarea>
						@error('deskKategori')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div>
				</div>
				<div class="form-actions">
					<button type="submit" class="btn btn-primary">Simpan</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection
<!-- </body>
</html> -->

resources/views/admin/category/index.blade.php
<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1"> -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> -->
<!-- </head>
<body>

<div class="container"> -->
@extends("admin.layout.conquer")

@section("left_sidebar")
<li class="sidebar-toggler-wrapper">
    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
    <div class="sidebar-toggler">
    </div>
    <div class="clearfix">
    </div>
    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
</li>
<li class="sidebar-search-wrapper">
    <form class="search-form" role="form" action="index.html" method="get">
        <div class="input-icon right">
            <i class="icon-magnifier"></i>
            <input type="text" class="form-control" name="query" placeholder="Search...">
        </div>
    </form>
</li>
<li>
    <a href="{{url('/admin')}}">
    <i class="icon-home"></i>
    <span class="title">Dashboard</span>
    <span class="arrow"></span>
    </a>
</li>
<li class="active">
    <a href="{{route('categories.index')}}">
        <i class="icon-layers"></i>
        Kategori</a>
    </a>
</li>
<li>
    <a href="{{route('products.index')}}">
        <i class="icon-present"></i>
        Produk</a>
    </a>
</li>
<li >
    <a href="{{route('generals.index')}}">
        <i class="icon-docs"></i>
        Kontak</a>
</li>
@endsection

@section("konten")
<div class="page-content">
  <h2>Daftar Kategori</h2>
  <div>
	      <a type= "button" href="{{route('categories.create')}}" class="btn btn-fit-height default">
					+ TAMBAH DAFTAR KATEGORI
				</a>
   </div>

   @if(session('status'))
    <div class="alert alert-success">
      {{ session('status') }}
    </div>
  @endif

  @if (session('statushapus'))
    <div class="alert alert-danger">
      {{ session('statushapus') }}
    </div>
  @endif

  <!-- <p>The .table class adds basic styling (light padding and only horizontal dividers) to a table:</p>              -->
  <table class="table">
    <thead>
      <tr>
        <!-- <th>ID</th> -->
        <th>Gambar</th>
        <th>Nama</th>
        <th>Deskripsi</th>
        <th>Daftar Produk</th>
        <th>Aksi</th>
      </tr>
    </thead>
    <tbody>
      @foreach($data as $d) 
      <tr>
        <!-- <td>{{ $d->idcategories }}</td> -->
        <td>
          @if ($d->gambar_kategori)
            <button type="button" style="background-color: Transparent; background-repeat:no-repeat; border: none; cursor:pointer; overflow: hidden;">
              <img src="{{ asset('storage/'.$d->gambar_kategori) }}" style="max-height:100px" alt="" data-toggle="modal" href="#detail_{{$d->idcategories}}">
            </button>
            <div class="modal fade" id="detail_{{$d->idcategories}}" tabindex="-1" role="basic" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                      <h4 class="modal-title">{{ $d->nama_kategori }}</h4>
                    </div>
                    <div class="modal-body">
                      <img src="{{ asset('storage/'.$d->gambar_kategori) }}" style="width: 60%; display: block; margin-left: auto; margin-right: auto;" alt=""/>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
                    </div>
                  </div>
              </div>
            </div>
          @endif
        </td>
        <td>{{ $d->nama_kategori }}</td>
        <td>{{ $d->deskripsi_kategori }}</td>
        <td>
          @foreach($d->products as $p) 
            {{ $p->nama_produk }};
          @endforeach
        </td>
        <td>
          <a class="btn btn-success" href="{{ route('categories.edit', $d->idcategories) }}">Ubah</a> <br> <br>
          <form method="POST" action="{{route('categories.destroy' , $d->idcategories)}}">
            @method('DELETE')
            @csrf
            <input class="btn btn-danger" type="SUBMIT" value="Hapus"
              onclick="if(!confirm('Apakah Anda yakin?')) {return false;}">
          </form>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
</div>
@endsection

<!-- </body>
</html> -->