routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//admin
Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function(){
    Route::get('/admin', function () {
        return view('admin/welcome');
    });
    
    Route::resource('products','ProductController');
    Route::resource('categories','CategoryController');
    Route::resource('generals','GeneralController');
    Route::resource('admin', 'VisitorController');
});


//customer
Route::resource('/', 'CustomerController')->names([
    'index' => 'home customer',
    // 'indexkategori' => 'indexkategoricust',
    // 'indexproduk' => 'indexprodukcust',
    // 'indexkontak' => 'indexkontakcust'
]);
// Route::resource('/', 'VisitorController');
Route::get('kategori/', 'CustomerController@indexkategori')->name("kategoricust");
Route::get('kategori/{nama_kategori}/', 'CustomerController@detailkategori')->name("listkategoriproduk");
Route::get('produk/', 'CustomerController@indexproduk')->name("produkcust");
Route::get('produk/{nama_produk}/', 'CustomerController@detailproduk')->name('detailproduk');
Route::get('kontak/', 'CustomerController@indexkontak')->name("kontakcust");

app/General.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class General extends Model
{
    protected $table = 'generals';

    // primary key pada database yaitu generals (default dari laravel yaitu id)
    protected $primaryKey = 'idgenerals';

    public $timestamps = false;
}

app/Http/Controllers/GeneralController.php
<?php

namespace App\Http\Controllers;

use App\General;
use Illuminate\Http\Request;
use DB;

class GeneralController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.general.index',['data'=>General::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\General  $general
     * @return \Illuminate\Http\Response
     */
    public function show(General $general)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\General  $general
     * @return \Illuminate\Http\Response
     */
    public function edit(General $general)
    {
        $data = $general;
        return view('admin/general/editform',compact('data'));
    }

    public function update(Request $request, General $general)
    {
        $request->validate([
            'almtGeneral' => 'required',
            'almturlGeneral' => 'required',
            'notelpGeneral' => 'required',
            'emailGeneral' => 'required',
        ], [
            'almtGeneral.required' => 'Alamat tidak boleh kosong',
            'almturlGeneral.required' => 'URL alamat tidak boleh kosong',
            'notelpGeneral.required' => 'Nomor telepon tidak boleh kosong',
            'emailGeneral.required' => 'E-Mail tidak boleh kosong',
        ]);     
        
        $general->alamat = $request->get('almtGeneral');
        $general->alamat_url = $request->get('almturlGeneral');
        $general->no_telp = $request->get('notelpGeneral');
        $general->email = $request->get('emailGeneral');
        $general->save();
        
        return redirect()->route('generals.index')->with('status', 'Data kontak berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\General  $general
     * @return \Illuminate\Http\Response
     */
    public function destroy(General $general)
    {
        //
    }
}

resources/views/admin/general/editform.blade.php
@extends("admin.layout.conquer")

@section("left_sidebar")
<li class="sidebar-toggler-wrapper">
    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
    <div class="sidebar-toggler">
    </div>
    <div class="clearfix">
    </div>
    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
</li>
<li class="sidebar-search-wrapper">
    <form class="search-form" role="form" action="index.html" method="get">
        <div class="input-icon right">
            <i class="icon-magnifier"></i>
            <input type="text" class="form-control" name="query" placeholder="Search...">
        </div>
    </form>
</li>
<li>
    <a href="{{url('/admin')}}">
    <i class="icon-home"></i>
    <span class="title">Dashboard</span>
    <span class="selected"></span>
    </a>
</li>
<li>
    <a href="{{route('categories.index')}}">
        <i class="icon-layers"></i>
        Kategori</a>
    </a>
</li>
<li>
    <a href="{{route('products.index')}}">
        <i class="icon-present"></i>
        Produk</a>
    </a>
</li>
<li class="active">
    <a href="{{route('generals.index')}}">
        <i class="icon-docs"></i>
        Kontak</a>
</li>
@endsection

@section("konten")
<div class="page-content">
<div class="portlet">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-reorder"></i> Ubah Data Kontak
			</div>
		</div>
		<div class="portlet-body form">
			<form method="POST" action="{{ route('generals.update', $data->idgenerals) }}" enctype="multipart/form-data">
			@csrf
			@method("PUT")
				<div class="form-body">
					<div class="form-group">
						<label for="almtGeneral">Alamat</label>
						<input type="text" class="form-control @error('almtGeneral') is-invalid @enderror" name="almtGeneral" value="{{ old('almtGeneral', $data->alamat) }}" placeholder="Isikan alamat Anda">
						@error('almtGeneral')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div><br>
					<div class="form-group">
						<label for="almturlGeneral">URL Alamat    &nbsp;(Dapat diambil melalui website <a href="https://google-map-generator.com/">https://google-map-generator.com/</a> dengan cara memasukkan alamat yang diinginkan, klik Get HTML-Code dan tempelkan URL yang berada dalam src)</label>
						<input type="text" class="form-control @error('almturlGeneral') is-invalid @enderror" name="almturlGeneral" value="{{ old('almturlGeneral', $data->alamat_url) }}" placeholder="Contoh: https://maps.google.com/maps?q=2880%20Broadway,%20New%20York&t=&z=13&ie=UTF8&iwloc=&output=embed">
						@error('almturlGeneral')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div><br>
                    <div class="form-group">
						<label for="notelpGeneral">Nomor Telepon</label>
						<input type="text" class="form-control @error('notelpGeneral') is-invalid @enderror" name="notelpGeneral" value="{{ old('notelpGeneral', $data->no_telp) }}" placeholder="Isikan nomor telepon Anda">
						@error('notelpGeneral')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div><br>
                    <div class="form-group">
						<label for="emailGeneral">E-Mail</label>
						<input type="text" class="form-control @error('emailGeneral') is-invalid @enderror" name="emailGeneral" value="{{ old('emailGeneral', $data->email) }}" placeholder="Isikan E-Mail Anda">
						@error('emailGeneral')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div><br>
				<div class="form-actions">
					<button type="submit" class="btn btn-primary">Simpan</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/admin/general/index.blade.php
@extends("admin.layout.conquer")

@section("left_sidebar")
<li class="sidebar-toggler-wrapper">
    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
    <div class="sidebar-toggler">
    </div>
    <div class="clearfix">
    </div>
    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
</li>
<li class="sidebar-search-wrapper">
    <form class="search-form" role="form" action="index.html" method="get">
        <div class="input-icon right">
            <i class="icon-magnifier"></i>
            <input type="text" class="form-control" name="query" placeholder="Search...">
        </div>
    </form>
</li>
<li>
    <a href="{{url('/admin')}}">
    <i class="icon-home"></i>
    <span class="title">Dashboard</span>
    <span class="selected"></span>
    </a>
</li>
<li>
    <a href="{{route('categories.index')}}">
        <i class="icon-layers"></i>
        Kategori</a>
    </a>
</li>
<li>
    <a href="{{route('products.index')}}">
        <i class="icon-present"></i>
        Produk</a>
    </a>
</li>
<li class="active">
    <a href="{{route('generals.index')}}">
        <i class="icon-docs"></i>
        Kontak</a>
</li>
@endsection

@section("konten")
<div class="page-content">
  <h2>Kontak</h2>
   @if(session('status'))
    <div class="alert alert-success">
      {{ session('status') }}
    </div>
  @endif

  <!-- <p>The .table class adds basic styling (light padding and only horizontal dividers) to a table:</p>              -->
  <table class="table">
    @foreach($data as $d)
      <tr>
        <th>Alamat</th>
        <td>{{ $d->alamat }}</td>
      </tr>
      <tr>
        <th>URL Alamat</th>
        <td>{{ $d->alamat_url }}</td>
      </tr>
      <tr>
        <th>Nomor Telepon</th>
        <td>{{ $d->no_telp }}</td>
      </tr>
      <tr>
        <th>E-Mail</th>
        <td>{{ $d->email }}</td>
      </tr>
      <tr>
        <th>Aksi</th>
        <td><a class="btn btn-success" href="{{ route('generals.edit', $d->idgenerals) }}">Ubah</a></td>
      </tr>
    @endforeach
  </table>
</div>
@endsection