routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//admin
Auth::routes();

// Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function(){
    Route::get('/admin', function () {
        return view('admin/welcome');
    });
    
    Route::resource('products','ProductController');
    Route::resource('categories','CategoryController');
    Route::resource('generals','GeneralController');
    Route::resource('admin', 'VisitorController');
});


//customer
Route::resource('/', 'CustomerController')->names([
    'index' => 'home customer',
    // 'indexkategori' => 'indexkategoricust',
    // 'indexproduk' => 'indexprodukcust',
    // 'indexkontak' => 'indexkontakcust'
]);
// Route::resource('/', 'VisitorController');
Route::get('kategori/', 'CustomerController@indexkategori')->name("kategoricust");
Route::get('kategori/{nama_kategori}/', 'CustomerController@detailkategori')->name("listkategoriproduk");
Route::get('produk/', 'CustomerController@indexproduk')->name("produkcust");
Route::get('produk/{nama_produk}/', 'CustomerController@detailproduk')->name('detailproduk');
Route::get('kontak/', 'CustomerController@indexkontak')->name("kontakcust");

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'products';

    // primary key pada database yaitu idproducts (default dari laravel yaitu id)
    protected $primaryKey = 'idproducts';

     // di product kita bisa ambil category, karena 1 produk punya 1 kategori maka pake belongsTo
    // nama fungsi category bebas, yang penting esensinya satu kategori 
    public function category() {
        //parameter berisi namespace\namaModel
        return $this->belongsTo("App\Category","category_id");
    }

    public $timestamps = false; //biar nggak error pas tambah supplier karena default dari laravel pakai timestamp, sedangkan kita ngga pakai timestamp
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use DB;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //Query bulider
        $queryBuilder = DB::table('products')
                        ->join("categories","products.categories_id","=","categories.idcategories")->get();

        //Passing data ke view
        //Cara 2 dengan sintaks array. Berarti variabel queryBuilder nanti hanya dikenali
        //pada Controller dan pada View diubah nama menjadi data
        return view('admin.product.index',['data'=>$queryBuilder]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //tampilkan data kategori sebagai foreign key
        $datakategori = Category::all();
        return view('admin.product.createform', compact('datakategori'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // return $request->file('image')->store('imageProducts');

        //untuk validasi saat user mengisi data, apabila ada yang masih kosong dimunculkan pesan error
        $request->validate([
            'nmProduk' => 'required',
            'hrgProduk' => 'required',
            'image' => 'required|image|file|max:10240',
            'deskProduk' => 'required',
            'ktgrProduk'  => 'required',
        ], [
            'nmProduk.required' => 'Nama produk tidak boleh kosong',
            'hrgProduk.required' => 'Harga produk tidak boleh kosong',
            'image.required' => 'Gambar produk tidak boleh kosong',
            'deskProduk.required' => 'Deskripsi produk tidak boleh kosong',
            'ktgrProduk.required'  => 'Kategori produk tidak boleh kosong',
        ]);             
        
        // New Produk berarti artinya new Data Kategori (insert)
        $data = new Product();

        // $data->[nama_kolom_pada_db] = $request->get('[name dari input text]')
        $data->nama_produk = $request->get('nmProduk');
        $data->harga_produk = $request->get('hrgProduk');
        if($request->file('image')) {
            $data['gambar_produk'] = $request->file('image')->store('imageProducts');
        }
        $data->deskripsi_produk = $request->get('deskProduk');
        $data->ketersediaan = $request->get('ktrsProduk');
        $data->tampil = $request->get('tplProduk');
        $data->categories_id = $request->get('ktgrProduk');
        $data->save();
        
        //akan memanggil route produk index yang akan kembali ke halaman utama Produk 
        //dengan menambahkan session status yang isinya berhasil ditambahkan Produk baru
        //with = membuat session sementara bernama status yg menampilkan berhasilnya ditambahkan data Produk 
        return redirect()->route('products.index')->with('status','Data Produk berhasil ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $data = $product;
        $datakategori = Category::all();
        return view('admin/product/editform',compact('data', 'datakategori'));
    }

    public function update(Request $request, Product $product)
    {
        $request->validate([
            'nmProduk' => 'required',
            'hrgProduk' => 'required',
            'image' => 'image|file|max:10240',
            'deskProduk' => 'required',
            'ktgrProduk'  => 'required',
        ], [
            'nmProduk.required' => 'Nama produk tidak boleh kosong',
            'hrgProduk.required' => 'Harga produk tidak boleh kosong',
            'deskProduk.required' => 'Deskripsi produk tidak boleh kosong',
            'ktgrProduk.required'  => 'Kategori produk tidak boleh kosong',
        ]);

        $product->nama_produk = $request->get('nmProduk');
        $product->harga_produk = $request->get('hrgProduk');
        if($request->file('image')) {
            if($request->oldImage) {
                Storage::delete($request->oldImage);
            }
            $product['gambar_produk'] = $request->file('image')->store('imageProducts'); 
        }
        $product->deskripsi_produk = $request->get('deskProduk');
        $product->ketersediaan = $request->get('ktrsProduk');
        $product->tampil = $request->get('tplProduk');
        $product->categories_id = $request->get('ktgrProduk');
        $product->save();
        
        return redirect()->route('products.index')->with('status', 'Data produk berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        if($product->gambar_produk) { //delete file gambar
            Storage::delete($product->gambar_produk);
        }
        $product->delete();
        return redirect()->route('products.index')->with('statushapus', 'Data produk berhasil dihapus');
    }
}

resources/views/admin/product/createform.blade.php
<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1"> -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> -->
<!-- </head>
<body>

<div class="container"> -->
@extends("admin.layout.conquer")

@section("left_sidebar")
<li class="sidebar-toggler-wrapper">
    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
    <div class="sidebar-toggler">
    </div>
    <div class="clearfix">
    </div>
    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
</li>
<li class="sidebar-search-wrapper">
    <form class="search-form" role="form" action="index.html" method="get">
        <div class="input-icon right">
            <i class="icon-magnifier"></i>
            <input type="text" class="form-control" name="query" placeholder="Search...">
        </div>
    </form>
</li>
<li>
    <a href="{{url('/admin')}}">
    <i class="icon-home"></i>
    <span class="title">Dashboard</span>
    <span class="selected"></span>
    </a>
</li>
<li>
    <a href="{{route('categories.index')}}">
        <i class="icon-layers"></i>
        Kategori</a>
    </a>
</li>
<li class="active">
    <a href="{{route('products.index')}}">
        <i class="icon-present"></i>
        Produk</a>
    </a>
</li>
<li >
    <a href="{{route('generals.index')}}">
        <i class="icon-docs"></i>
        Kontak</a>
</li>
@endsection

@section("konten")
<div class="page-content">
<div class="portlet">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-reorder"></i> Tambah Data Produk
			</div>
		</div>
		<div class="portlet-body form">
			<form method="POST" action="{{ route('products.store') }}" enctype="multipart/form-data" >
			@csrf
				<div class="form-body">
					<div class="mb-3">
						<label for="image" class="form-label">Gambar</label> 
						<input class="form-control" type="file" id="image" name="image" onchange="document.getElementById('img-preview').src = window.URL.createObjectURL(this.files[0])">
						@error('image')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
						<img class="img-fluid" id="img-preview" style="max-height:400px">
					</div><br>
					<div class="form-group">
						<label for="nmProduk">Nama</label>
						<input type="text" class="form-control @error('nmProduk') is-invalid @enderror" name="nmProduk" value="{{ old('nmProduk') }}" placeholder="Isikan nama produk Anda">
						@error('nmProduk')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div><br>
					<div class="form-group">
						<label for="hrgProduk">Harga</label> (Rp)
						<input type="number" class="form-control @error('hrgProduk') is-invalid @enderror" name="hrgProduk" value="{{ old('hrgProduk') }}"  placeholder="Isikan harga produk Anda" min="0">
						@error('hrgProduk')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div><br>
					<div class="form-group">
						<label for="deskProduk">Deskripsi</label>
						<textarea class="form-control @error('deskProduk') is-invalid @enderror" name="deskProduk" placeholder="Isikan deskripsi produk Anda" rows="3">{{ old('deskProduk') }}</textarea>
						@error('deskProduk')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div><br>
					<div class="form-group row">
						<label for="name" class="col-md-4 col-form-label">Status Ketersediaan</label>
						<div class="col-md-12">
							<select name="ktrsProduk" id="ktrsProduk" class="form-control">
								<option value="tersedia">Tersedia</option>
								<option value="tidak tersedia">Tidak Tersedia</option>
							</select>
						</div>
					</div><br>
					<div class="form-group row">
						<label for="name" class="col-md-4 col-form-label">Tampilkan Produk pada Halaman Konsumen</label>
						<div class="col-md-12">
							<select name="tplProduk" id="tplProduk" class="form-control">
								<option value="ya">Ya</option>
								<option value="tidak">Tidak</option>
							</select>
						</div>
					</div><br>				
					<div class="form-group row">
						<label for="name" class="col-md-4 col-form-label">Kategori Produk</label>
						<div class="col-md-12">
							<select name="ktgrProduk" id="ktgrProduk" class="form-control @error('ktgrProduk') is-invalid @enderror">
								<option value="">== Pilih Kategori ==</option>
								@foreach($datakategori as $dk)
									<option value="{{ $dk->idcategories }}" {{ old('ktgrProduk') == $dk->idcategories ? 'selected' : null }}>{{ $dk->nama_kategori }}</option>
								@endforeach
							</select>
							@error('ktgrProduk')
								<div class="invalid-feedback" style="color:red">{{ $message }}</div>
							@enderror
						</div>
					</div>
				</div>
				<div class="form-actions">
					<button type="submit" class="btn btn-primary">Simpan</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection
<!-- </body>
</html> -->

resources/views/admin/product/editform.blade.php
<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1"> -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> -->
<!-- </head>
<body>

<div class="container"> -->
@extends("admin.layout.conquer")

@section("left_sidebar")
<li class="sidebar-toggler-wrapper">
    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
    <div class="sidebar-toggler">
    </div>
    <div class="clearfix">
    </div>
    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
</li>
<li class="sidebar-search-wrapper">
    <form class="search-form" role="form" action="index.html" method="get">
        <div class="input-icon right">
            <i class="icon-magnifier"></i>
            <input type="text" class="form-control" name="query" placeholder="Search...">
        </div>
    </form>
</li>
<li>
    <a href="{{url('/admin')}}">
    <i class="icon-home"></i>
    <span class="title">Dashboard</span>
    <span class="selected"></span>
    </a>
</li>
<li>
    <a href="{{route('categories.index')}}">
        <i class="icon-layers"></i>
        Kategori</a>
    </a>
</li>
<li class="active">
    <a href="{{route('products.index')}}">
        <i class="icon-present"></i>
        Produk</a>
    </a>
</li>
<li >
    <a href="{{route('generals.index')}}">
        <i class="icon-docs"></i>
        Kontak</a>
</li>
@endsection

@section("konten")
<div class="page-content">
<div class="portlet">
		<div class="portlet-title">
			<div class="caption">
				<i class="fa fa-reorder"></i> Ubah Data Produk
			</div>
		</div>
		<div class="portlet-body form">
			<form method="POST" action="{{ route('products.update', $data->idproducts) }}" enctype="multipart/form-data">
			@csrf
			@method("PUT")
				<div class="form-body">
					<div class="mb-3">
						<label for="image" class="form-label">Gambar</label> 
						<input type="hidden" name="oldImage" value="{{ $data->gambar_produk }}"> <!-- menyimpan image lama -->
						<input class="form-control" type="file" id="image" name="image" onchange="document.getElementById('img-preview').src = window.URL.createObjectURL(this.files[0])">
						@if($data->gambar_produk)
							<img src="{{ asset('storage/' . $data->gambar_produk) }}" class="img-fluid" id="img-preview" style="max-height:400px">
						@else
							<img class="img-fluid" id="img-preview" style="max-height:400px">
							@error('image')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
						@endif
					</div><br>
					<div class="form-group">
						<label for="nmProduk">Nama</label>
						<input type="text" class="form-control @error('nmProduk') is-invalid @enderror" name="nmProduk" value="{{ old('nmProduk', $data->nama_produk) }}" placeholder="Isikan nama produk Anda">
						@error('nmProduk')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div><br>
					<div class="form-group">
						<label for="hrgProduk">Harga</label> (Rp)
						<input type="number" class="form-control @error('hrgProduk') is-invalid @enderror" name="hrgProduk" value="{{ old('hrgProduk', $data->harga_produk) }}"  placeholder="Isikan harga produk Anda" min="0">
						@error('hrgProduk')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div><br>
					<div class="form-group">
						<label for="deskProduk">Deskripsi</label>
						<textarea class="form-control @error('deskProduk') is-invalid @enderror" name="deskProduk" placeholder="Isikan deskripsi produk Anda" rows="3">{{ old('deskProduk', $data->deskripsi_produk) }}</textarea>
						@error('deskProduk')
							<div class="invalid-feedback" style="color:red">{{ $message }}</div>
						@enderror
					</div><br>
					<div class="form-group row">
						<label for="name" class="col-md-4 col-form-label">Status Ketersediaan</label>
						<div class="col-md-12">
							<select name="ktrsProduk" id="ktrsProduk" class="form-control">
								<option value="tersedia" {{ old('ktrsProduk', $data->ketersediaan == 'tersedia' ? 'selected' : '' ) }}>Tersedia</option>
								<option value="tidak tersedia" {{ old('ktrsProduk', $data->ketersediaan == 'tidak tersedia' ? 'selected' : '' ) }}>Tidak Tersedia</option>
							</select>
						</div>
                	</div><br>
					<div class="form-group row">
						<label for="name" class="col-md-4 col-form-label">Tampilkan Produk pada Halaman Konsumen</label>
						<div class="col-md-12">
							<select name="tplProduk" id="tplProduk" class="form-control">
								<option value="ya" {{ old('tplProduk', $data->tampil == 'ya' ? 'selected' : '' ) }}>Ya</option>
								<option value="tidak" {{ old('tplProduk', $data->tampil == 'tidak' ? 'selected' : '' ) }}>Tidak</option>
							</select>
						</div>
                	</div><br>
						<div class="form-group row">
						<label for="name" class="col-md-4 col-form-label">Kategori Produk</label>
						<div class="col-md-12">
							<select name="ktgrProduk" id="ktgrProduk" class="form-control @error('ktgrProduk') is-invalid @enderror">
								<option value="" >== Pilih Kategori ==</option>
								@foreach($datakategori as $dk)
								<option value="{{ $dk->idcategories }}" {{ old('ktgrProduk', $data->categories_id) == $dk->idcategories ? 'selected' : null }}>{{ $dk->nama_kategori }}</option>
								@endforeach
							</select>
							@error('ktgrProduk')
								<div class="invalid-feedback" style="color:red">{{ $message }}</div>
							@enderror
						</div>
                	</div>
				</div>
				<!--  -->
				<div class="form-actions">
					<button type="submit" class="btn btn-primary">Simpan</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection
<!-- </body>
</html> -->

resources/views/admin/product/index.blade.php
<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1"> -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> -->
<!-- </head>
<body>

<div class="container">  -->
@extends("admin.layout.conquer")

@section("left_sidebar")
<li class="sidebar-toggler-wrapper">
    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
    <div class="sidebar-toggler">
    </div>
    <div class="clearfix">
    </div>
    <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
</li>
<li class="sidebar-search-wrapper">
    <form class="search-form" role="form" action="index.html" method="get">
        <div class="input-icon right">
            <i class="icon-magnifier"></i>
            <input type="text" class="form-control" name="query" placeholder="Search...">
        </div>
    </form>
</li>
<li>
    <a href="{{url('/admin')}}">
    <i class="icon-home"></i>
    <span class="title">Dashboard</span>
    <span class="selected"></span>
    </a>
</li>
<li>
    <a href="{{route('categories.index')}}">
        <i class="icon-layers"></i>
        Kategori</a>
    </a>
</li>
<li class="active">
    <a href="{{route('products.index')}}">
        <i class="icon-present"></i>
        Produk</a>
    </a>
</li>
<li >
    <a href="{{route('generals.index')}}">
        <i class="icon-docs"></i>
        Kontak</a>
</li>
@endsection

@section("konten")
<div class="page-content">
  <h2>Daftar Produk</h2>
  <div>
    <a type= "button" href="{{route('products.create')}}" class="btn btn-fit-height default">
      + TAMBAH DAFTAR PRODUK
    </a>
  </div>

  @if(session('status'))
    <div class="alert alert-success">
      {{ session('status') }}
    </div>
  @endif

  @if (session('statushapus'))
    <div class="alert alert-danger">
      {{ session('statushapus') }}
    </div>
  @endif

  <!-- <p>The .table class adds basic styling (light padding and only horizontal dividers) to a table:</p>             -->
  <table class="table">
    <thead>
      <tr>
        <!-- <th>ID</th> -->
        <th>Gambar</th>
        <th>Nama</th>
        <th>Harga</th>
        <th>Deskripsi</th>
        <th>Status Ketersediaan</th>
        <th>Tampilkan Produk pada Halaman Konsumen</th>
        <th>Kategori Produk</th>
        <th>Aksi</th>
      </tr>
    </thead>
    <tbody>
      @foreach($data as $d)
      <tr>
        <!-- <td>{{ $d->idproducts }}</td> -->
        <td>
          @if ($d->gambar_produk)
          <button type="button" style="background-color: Transparent; background-repeat:no-repeat; border: none; cursor:pointer; overflow: hidden;">
            <img src="{{ asset('storage/'.$d->gambar_produk) }}" style="max-height:100px" alt="" data-toggle="modal" href="#detail_{{$d->idproducts}}">
          @endif
          </button>
          <div class="modal fade" id="detail_{{$d->idproducts}}" tabindex="-1" role="basic" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                      <h4 class="modal-title">{{ $d->nama_produk }}</h4>
                    </div>
                    <div class="modal-body">
                      <img src="{{ asset('storage/'.$d->gambar_produk) }}" style="width: 60%; display: block; margin-left: auto; margin-right: auto;" alt=""/>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
                    </div>
                  </div>
              </div>
            </div>
        </td>
        <td>{{ $d->nama_produk }}</td>
        <td>{{ $d->harga_produk }}</td>
        <td>{{ $d->deskripsi_produk }}</td>
        <td>{{ $d->ketersediaan }}</td>
        <td>{{ $d->tampil }}</td>
        <td>{{ $d->nama_kategori }}</td>
        <td><a class="btn btn-success" href="{{ route('products.edit', $d->idproducts) }}">Ubah</a> <br> <br>
          <form method="POST" action="{{route('products.destroy' , $d->idproducts)}}">
              @method('DELETE')
              @csrf
              <input class="btn btn-danger" type="SUBMIT" value="Hapus"
                onclick="if(!confirm('Apakah Anda yakin?')) {return false;}">
            </form>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
</div>
@endsection
<!-- </body>
</html> -->